name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.0.0
          
      - name: Install dependencies
        run: poetry install
        
      - name: Run Black
        run: poetry run black . --check
        
      - name: Run Ruff
        run: poetry run ruff check .
        
      - name: Run MyPy
        run: poetry run mypy .